# Generated by Django 4.1.7 on 2023-02-28 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_todoitem_todo_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="user",
            new_name="owner",
        ),
    ]
